language: python
python:
  - "3.7"
sudo: required
install:
  - pip install flask
script:
  - python test.py
deploy:
  provider: heroku
  api_key:
    secure: kWj3auzzJdcwBuYbD5C3wkSGv0txxVUxickDPrT+koNuxqfPRt4SyAl7xQPTYGhJF4/yBovwJyXIIFgDOlnmlkcgVGbHNkQtVbfgVLtwEOYOwBEusU7dV5WOnSBSLLFBHM7oQ93etd2Q0jgSxODIk0KfKTTfPsJgWdpAoUZ2WZyt5hL6C/wi5NPoa1CNuMLubjjrKpVrcrO+dFaAsYLZsnnFbXrfZqGeSi6Z6+giN8ihaGI4Z90O8EyXHLLIk53O960/Aumdk+sL5GiECGvjw3SqEcWeqPEt4slDHgGeyo6Xsf6F0NTD1xqnb5ezhhgrVnmWfk3i/RkUgDeAm5Kk6JIACsFneAgyndYhKsHkj81JJKAMJj60KrNZM2o6XZr5DoHO6iI5kjUpFA1uEuveBJ4dFbslJESq+uNjDyqhnYoyr78Kdu0TnvJKhzyo2sbPEDQM9NHIoWywYWKWF98kv/vHVPYqcep9v6BtqvH8hf7mt/CGMUqlYtGnJy8Zn1evvvfdlj7hsKNAbw5kSTfFPV4Hg4qGkZr33XZZgBnRBrofDWxZLVVJxuL5prfmiT1YBRwxkcwemLfefZL44jVnPPnKotakZh+TL0n8YBLqbj33Rg+MjOsIFVpA3hdkeexbQkLSqlgZJBR34hqlbxryzOaFg7552SGw4MSWUdCp0Uk=
  app: app4linux
